### ISSUE TITLE
Update error?

### ISSUE THREAD

**Issue by N6RFM** [daniestevez/galileo-osnma#23]
Hi Dani,

While attempting to update to the latest version, my practice has been to perform cargo clean, then cargo build  --release,  in the following folders -
/galileo-osnma
/galileo-osnma/galmon-osnma
/galileo-osnma/osnma-longan-nano
/galileo-osnma/osnma-longan-nano-client

all goes well except in the /galileo-osnma/osnma-longan-nano folder where I get an error near the end of the build.

Compiling riscv-rt-macros v0.2.1
error: instruction requires the following: 'M' (Integer Multiplication and Division) or 'Zmmul' (Integer Multiplication)
mul t0, t2, t0
^
error: instruction requires the following: 'M' (Integer Multiplication and Division) or 'Zmmul' (Integer Multiplication)
mul t0, t2, t0
^
error: instruction requires the following: 'M' (Integer Multiplication and Division) or 'Zmmul' (Integer Multiplication)
mul t0, t2, t0
^
    Finished release [optimized] target(s) in 13.01s

Despite this, I am able to build the firmware using the command from with the /galileo-osnma/osnma-longan-nano folder 

~/riscv-binutils-gdb/binutils/objcopy -O binary target/riscv32imac-unknown-none-elf/release/osnma-longan-nano firmware.bin

Any suggestions as to why this may be happening?  

Thanks,
Bob

**Comment by daniestevez** [comment]
I'm also getting that error, [even in CI](https://github.com/daniestevez/galileo-osnma/actions/runs/7581277584/job/20648575822#step:6:234). It seems that it is a problem with `riscv-rt`, a dependency. The problem seems harmless though. The firmware image builds and works just fine. I will try to replicate this problem in a minimal case and report upstream.

**Comment by N6RFM** [comment]
Thanks Dani.  In the meantime, I'll flash the update.

**Comment by N6RFM** [comment]
Hi Dani,
Realized that I had to update the public key.  Done.

There is also a file in the /galileo-osnma/osnma-longan-nano folder called merkle_tree_root.txt.  Is this where the new string copied from the Merkl_tree XML file is to be placed or should the entire line <TreeNode><j>4</j><i>0</i><lengthInBits>256</lengthInBits><x_ji>...</x_ji></TreeNode> be placed somewhere else?

I am now seeing a different error when doing a cargo clean then cargo build from the  /galileo-osnma/osnma-longan-nano folder.  This occurs near the end of the build process.  Is Rust looking for a file that's missing perhaps?  Thanks.  Bob

Compiling log v0.4.20
error: failed to run custom build command for `osnma-longan-nano v0.1.0 (/home/bob/galileo-osnma/osnma-longan-nano)`

Caused by:
  process didn't exit successfully: `/home/bob/galileo-osnma/osnma-longan-nano/target/release/build/osnma-longan-nano-701dfc9cb301faee/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/home/bob/galileo-osnma/osnma-longan-nano/target/riscv32imac-unknown-none-elf/release/build/osnma-longan-nano-ff52b1e4d79b3421/out
  cargo:rerun-if-changed=memory-cb.x

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:53:74
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
bob@bob:~/galileo-osnma/osnma-longan-nano$

**Comment by N6RFM** [comment]
Thank you Dani!  Now working.  :-)

**Comment by daniestevez** [comment]
Closing, since this is working now.
