### ISSUE TITLE
86.82.68.237 status?

### ISSUE THREAD

**Issue by K4KDR** [daniestevez/galileo-osnma#9]
The Galmon Galileo navigation data feed, as in:

`nc 86.82.68.237 10000`

... has not been responding for the past day or so.

Is an update required to the address to use for that source?

Thanks!

**Comment by daniestevez** [comment]
I don't know. This is a somewhat experimental service provided by Galmon, so it may or may not work. It's worth to monitor the @GalileoSats account on Twitter for any news about this service (and perhaps give it a friendly notice if this stays broken for more days).

**Comment by K4KDR** [comment]
Sorry for the late follow-up.  The service came back online.  I will close this issue.

Thanks!
